# 통합 전처리 설정 / Unified Preprocessing Configuration
# 모든 모델에 공통으로 사용

# ROI 검출 설정 / ROI Detection
roi:
  method: 'auto'
  fallback_bbox: null
  padding: 20

# 종횡비 정규화 / Aspect Ratio Normalization
aspect_ratio:
  target_ratio: 2.0
  method: 'pad'
  pad_value: 0

# 해상도 표준화 / Resolution Standardization
resolution:
  target_width: 2048
  target_height: 1024
  interpolation: 'lanczos'
  maintain_aspect: true

# 밝기 정규화 / Brightness Normalization
brightness_normalization:
  enabled: true
  method: 'zscore'  # 'zscore', 'minmax', 'histogram', 'adaptive'
  target_mean: 127.5
  target_std: 50.0
  clip_range: [0, 255]

# 히스토그램 매칭 / Histogram Matching
histogram_matching:
  enabled: false

# CLAHE (Contrast Limited Adaptive Histogram Equalization)
clahe:
  enabled: true
  clip_limit: 2.0
  tile_size: [8, 8]

# 노이즈 제거 / Denoising
denoising:
  enabled: false
  method: 'bilateral'
  strength: 3

# 샤프닝 / Sharpening
sharpening:
  enabled: false
  strength: 1.0

# 출력 설정 / Output
output:
  format: 'png'
  quality: 95
  bit_depth: 8

# 라벨 변환 / Label Transformation
labels:
  format: 'yolo'
  validate: true
  min_bbox_size: 5
  filter_invalid: true

# 품질 검증 / Quality Validation
validation:
  enabled: true
  min_resolution: [640, 320]
  max_resolution: [8192, 4096]
  min_brightness: 10
  max_brightness: 245
  blur_threshold: 50
